name: Market Trading Adapter
description: Chainlink External Adaptor for the World Trading Data API
node_identifier: fsmarket
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: WorldTradingData
    url: https://www.worldtradingdata.com/documentation
parameters:
  - endpoint stock
  - symbol stock symbol
