name: MarketTradingData
description: Chainlink External Adaptor for the World Trade Data API
node_identifier: Fourswords
platforms:
  - Docker
  - AWS Lambda
  - GCP Functions
data_sources:
  - name: WorldTradingData
    url: https://www.worldtradingdata.com/documentation
parameters:
  - endpoint stock
  - symbol stock symbol
